<a href="https://colab.research.google.com/github/Passonileticia/analise_vaquinhasolidaria/blob/main/aula_304.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np

from google.colab import files

upload = files.upload()

arquivo orientado a colocar porem não rodou, seguido caminho normal

In [38]:
df = pd.read_csv("/content/DataPrepFinal.csv")

1.   unnamed - linha sem necessidade
2.  name - nome da vaquinha (dados não estruturados em grande parte das análises não tem serventia)
3. category - categoria
4. main_category - categoria principal
5. currency - moeda principal
6. deadline - tempo maximo de arrecadação
7. goal - objetivo
8. launched - quando lançaram
9. pledged - valor alcançado
10. state - status
11. backers - quantos apoiadores
12. country - pais
13. usd pledged - valor levantado em dolar
14. usd_pledged_real - valor levantado em real
15. usd_goal_real - objetivo financeiro

In [39]:
df.head()

,Unnamed: 0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,09/10/15,100000,11/08/15 12:12,0,failed,0,GB,0.0,0,USD 153395
1,1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,01/11/17,3000000,02/09/17 04:43,242100,failed,15,US,10000.0,242100,USD 3000000
2,2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,26/02/13,4500000,12/01/13 00:20,22000,failed,3,US,22000.0,22000,USD 4500000
3,3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,16/04/12,500000,17/03/12 03:24,100,failed,1,US,100.0,100,USD 500000
4,4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,29/08/15,1950000,04/07/15 08:35,128300,canceled,14,US,128300.0,128300,USD 1950000

parte de retirada de colunas que não vou usar nessa analise

In [40]:
df = df.drop(columns=['Unnamed: 0','name','category','goal','pledged','usd pledged'])

In [41]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,USD 153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,USD 3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,USD 4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,USD 500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,USD 1950000

Puxo as informações para ver se ele tem algum valor nulo e para ver o tipo dos dados

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19463 entries, 0 to 19462
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19463 non-null  int64
 1   main_category     19463 non-null  object
 2   currency          19463 non-null  object
 3   deadline          19463 non-null  object
 4   launched          19463 non-null  object
 5   state             19463 non-null  object
 6   backers           19463 non-null  int64
 7   country           19463 non-null  object
 8   usd_pledged_real  19463 non-null  int64
 9   usd_goal_real     19463 non-null  object
dtypes: int64(3), object(7)
memory usage: 1.5+ MB

#Corrigir dados alterando o tipo dos dados

.apply(sum) -> posso aplicar uma função em cada linha

lambda -> cria uma função

x.strip('USD' ) -> remove caracteres do começo

#Não esquecer que para salvar deve declarar como VAR

In [43]:
df['usd_goal_real'] = df['usd_goal_real'].apply(lambda x: x.strip('USD '))

In [44]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15 12:12,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17 04:43,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13 00:20,failed,3,US,22000,4500000
3,1000007540,Music,USD,16/04/12,17/03/12 03:24,failed,1,US,100,500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15 08:35,canceled,14,US,128300,1950000

Remoção de um valor com um padrão utilizando o regex

In [45]:
df['launched'].str.replace(' \d\d:\d\d','', regex=True)

0        11/08/15
1        02/09/17
2        12/01/13
3        17/03/12
4        04/07/15
           ...
19458    27/07/15
19459    06/10/14
19460    31/03/11
19461    18/04/14
19462    05/12/11
Name: launched, Length: 19463, dtype: object

In [46]:
df['launched'] = df['launched'].str.replace(' \d\d:\d\d','', regex=True)

In [47]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,09/10/15,11/08/15,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,01/11/17,02/09/17,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,26/02/13,12/01/13,failed,3,US,22000,4500000
3,1000007540,Music,USD,16/04/12,17/03/12,failed,1,US,100,500000
4,1000011046,Film & Video,USD,29/08/15,04/07/15,canceled,14,US,128300,1950000

Transformando o tipo dos dados

.astype('int')
int - inteiro
float - numero flutuante
string - texto
bool - booleando (v e f)

In [48]:
df['usd_goal_real'] = df['usd_goal_real'].astype('int64')

para declarar data usamos o format=' ' , é dizer essa string é uma data, transforme ela em uma data

para data com pandas -> busca no google pandas datetime format codes

https://pandas.pydata.org/docs/reference/api/pandas.Period.strftime.html

or

In [49]:
df['deadline'] = pd.to_datetime(df['deadline'], format='%d/%m/%y')
df['launched'] = pd.to_datetime(df['launched'], format='%d/%m/%y')

In [50]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19463 entries, 0 to 19462
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19463 non-null  int64
 1   main_category     19463 non-null  object
 2   currency          19463 non-null  object
 3   deadline          19463 non-null  datetime64[ns]
 4   launched          19463 non-null  datetime64[ns]
 5   state             19463 non-null  object
 6   backers           19463 non-null  int64
 7   country           19463 non-null  object
 8   usd_pledged_real  19463 non-null  int64
 9   usd_goal_real     19463 non-null  int64
dtypes: datetime64[ns](2), int64(4), object(4)
memory usage: 1.5+ MB

Verificação do tempo que ficou aberto a campanha

se eu tiro o ".dt.days" ele mostra o valor da diferença em dias

Já declarando para criar uma nova coluna

In [52]:
df['time_range'] = (df['deadline'] - df['launched']).dt.days

In [53]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56

#Integrando uma nova base de dados que é a base da campanha

In [54]:
df_c = pd.read_csv('/content/campaign.csv')

#colunas
* id
* descrição do texto
* video
* imagem
* infografico
* reviews
* risco

In [55]:
df_c.head()

           ID  Text Description  Video  Image  Infographic  Reviews  Risks
0  1000002330                 1      1      1            1        0      1
1  1000003930                 1      1      1            1        1      0
2  1000004038                 1      0      1            1        0      1
3  1000007540                 1      1      0            1        0      0
4  1000011046                 1      0      1            0        0      0

In [56]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19463 entries, 0 to 19462
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19463 non-null  int64
 1   Text Description  19463 non-null  int64
 2   Video             19463 non-null  int64
 3   Image             19463 non-null  int64
 4   Infographic       19463 non-null  int64
 5   Reviews           19463 non-null  int64
 6   Risks             19463 non-null  int64
dtypes: int64(7)
memory usage: 1.0 MB

In [57]:
df_c['Video'].unique()

array([1, 0])

In [58]:
df_c = df_c.drop(columns=['Text Description'])

In [59]:
df_c.head()

           ID  Video  Image  Infographic  Reviews  Risks
0  1000002330      1      1            1        0      1
1  1000003930      1      1            1        1      0
2  1000004038      0      1            1        0      1
3  1000007540      1      0            1        0      0
4  1000011046      0      1            0        0      0

Juntar as tabelas tanto a principal quanto a secundaria pelo seu fator de similaridade/ chave (Id)

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

no caso vamos contar pela direita pelo df principal com base no id

In [60]:
df = df.merge(df_c, how= 'right', on=['ID'])

In [61]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks
0,1000002330,Publishing,GBP,2015-10-09,2015-08-11,failed,0,GB,0,153395,59,1,1,1,0,1
1,1000003930,Film & Video,USD,2017-11-01,2017-09-02,failed,15,US,242100,3000000,60,1,1,1,1,0
2,1000004038,Film & Video,USD,2013-02-26,2013-01-12,failed,3,US,22000,4500000,45,0,1,1,0,1
3,1000007540,Music,USD,2012-04-16,2012-03-17,failed,1,US,100,500000,30,1,0,1,0,0
4,1000011046,Film & Video,USD,2015-08-29,2015-07-04,canceled,14,US,128300,1950000,56,0,1,0,0,0

In [62]:
df_invest = pd.read_csv('/content/invested.csv')

In [63]:
df_invest.head()

           ID backedLocation  age
0  1000003930             BR   18
1  1000004038             US   57
2  1000007540             US   43
3  1000011046             BR   29
4  1000014025             BR   77

Nessa busca pode se perceber que na tabela de investidor temos a repedição de Id, uma vez que o id geral esta relacionado com as vaquinhas

In [64]:
df_invest.sort_values(by=['ID'])

               ID backedLocation  age
27400      106144             US   63
10585      106144            GBK   70
17409     1003381             BR   68
594       1003381             US   29
2925      1017454             US   62
...           ...            ...  ...
16812  1098729640            GBK   61
33627  1098729640            GBK   43
16814  1098735707             BR   66
33629  1098735707             US   62
35395  1098735707             US   63

[35396 rows x 3 columns]

In [65]:
df_invest.head()

           ID backedLocation  age
0  1000003930             BR   18
1  1000004038             US   57
2  1000007540             US   43
3  1000011046             BR   29
4  1000014025             BR   77

nesse processo vamos agrepar por 1 o que for de um determinado e 0 se não for de um determinado estado  
get_dumminies

codigo com o processo de conversao

In [66]:
df_invest = pd.get_dummies(df_invest, columns=['backedLocation'])
df_invest = df_invest.astype(int)

In [67]:
df_invest.head()

           ID  age  backedLocation_BR  backedLocation_GBK  backedLocation_US
0  1000003930   18                  1                   0                  0
1  1000004038   57                  0                   0                  1
2  1000007540   43                  0                   0                  1
3  1000011046   29                  1                   0                  0
4  1000014025   77                  1                   0                  0

In [68]:
df_invest.sort_values (by=['ID'])

,ID,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
27400,106144,63,0,0,1
10585,106144,70,0,1,0
17409,1003381,68,1,0,0
594,1003381,29,0,0,1
2925,1017454,62,0,0,1
...,...,...,...,...,...
16812,1098729640,61,0,1,0
33627,1098729640,43,0,1,0
16814,1098735707,66,1,0,0
33629,1098735707,62,0,0,1
35395,1098735707,63,0,0,1

feito media para ter uma estimativa sobre media de estafo e idade que ajudaram

In [69]:
df_invest = df_invest.groupby(by=['ID']).agg({'age':'mean','backedLocation_BR':'sum', 'backedLocation_GBK':'sum','backedLocation_US':'sum'})

In [70]:
df_invest.head()

          age  backedLocation_BR  backedLocation_GBK  backedLocation_US
ID
106144   66.5                  0                   1                  1
1003381  48.5                  1                   0                  1
1017454  41.5                  0                   0                  2
1024013  77.0                  2                   0                  0
1024208  71.0                  0                   1                  1

In [71]:
df = df.merge(df_invest, how='right', on='ID')

In [72]:
df.head()

,ID,main_category,currency,deadline,launched,state,backers,country,usd_pledged_real,usd_goal_real,time_range,Video,Image,Infographic,Reviews,Risks,age,backedLocation_BR,backedLocation_GBK,backedLocation_US
0,106144,Music,USD,2014-06-15,2014-05-16,failed,1,US,1500,180000,30,1,1,0,0,1,66.5,0,1,1
1,1003381,Music,USD,2012-07-19,2012-06-21,failed,30,US,115900,1000000,28,0,1,0,1,1,48.5,1,0,1
2,1017454,Film & Video,USD,2015-04-26,2015-04-20,successful,9,US,16700,100,6,1,0,1,0,1,41.5,0,0,2
3,1024013,Publishing,USD,2012-05-18,2012-04-03,failed,136,US,975805,4000000,45,1,1,1,0,0,77.0,2,0,0
4,1024208,Technology,USD,2014-09-11,2014-08-12,failed,5,US,15000,150000,30,0,1,1,0,0,71.0,0,1,1